name = "onotes"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
account_id = "fd68bd5ae8f7a9aa3f03ea057fcc3233"
route = "onotes.workers.dev/*"
kv_namespaces = [
  { binding = "ONOTES", id = "498f7faa083e4d1eb0b5ad9721cc294a" }
]
[site]
bucket = ".output/public"
